BitirmeFin/Kodlar/eBookSiteWebUI/Controllers/ChapterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eBookSiteWebUI.Entity;

namespace eBookSiteWebUI.Controllers
{
    public class ChapterController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Chapter
        public ActionResult Index()
        {
            var chapters = db.Chapters.Include(c => c.Novel);
            return View(chapters.ToList());
        }

        // GET: Chapter/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            return View(chapter);
        }

        // GET: Chapter/Create
        public ActionResult Create()
        {
            ViewBag.NovelId = new SelectList(db.Novels, "Id", "Name");
            return View();
        }

        // POST: Chapter/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Content,Date,ChapterCount,NovelId")] Chapter chapter)
        {
            if (ModelState.IsValid)
            {
                db.Chapters.Add(chapter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NovelId = new SelectList(db.Novels, "Id", "Name", chapter.NovelId);
            return View(chapter);
        }

        // GET: Chapter/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            ViewBag.NovelId = new SelectList(db.Novels, "Id", "Name", chapter.NovelId);
            return View(chapter);
        }

        // POST: Chapter/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Content,Date,ChapterCount,NovelId")] Chapter chapter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chapter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NovelId = new SelectList(db.Novels, "Id", "Name", chapter.NovelId);
            return View(chapter);
        }

        // GET: Chapter/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            return View(chapter);
        }

        // POST: Chapter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Chapter chapter = db.Chapters.Find(id);
            db.Chapters.Remove(chapter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BitirmeFin/Kodlar/eBookSiteWebUI/Controllers/NovelController.cs
using eBookSiteWebUI.Entity;
using eBookSiteWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBookSiteWebUI.Controllers
{
    public class NovelController : Controller
    {

        DataContext _context = new DataContext();


        // GET: Novel
        public ActionResult Index(int? id)
        {
            var novels = _context.Novels
                 .Where(i => i.isHome == true)
                 .Select(i => new NovelsModel()
                 {

                     Id = i.Id,
                     Name = i.Name,
                     Author = i.Author,
                     Status = i.Status,
                     Image = i.Image == null ? "1.jpg" : i.Image,
                     Summary = i.Summary.Length > 50 ? i.Summary.Substring(0, 47) + "..." : i.Summary,
                     GenreId = i.GenreId

                 }).ToList().AsQueryable();

            if (id!=null)
            {
                novels = novels.Where(i => i.GenreId == id);
            }

            return View(novels.ToList());
        }

        public ActionResult Details(int id)
        {
            return View(_context.Novels.Where(i=>i.Id==id).FirstOrDefault());
        }

        public ActionResult Chapter(int id)
        {
            return View(_context.Chapters.Where(i=>i.NovelId==id).FirstOrDefault());
        }

        public PartialViewResult GetGenres()
        {
            return PartialView(_context.Genres.ToList());
        }


    }
}

BitirmeFin/Kodlar/eBookSiteWebUI/Views/Novel/Chapter.cshtml
@using eBookSiteWebUI.Entity;
@model  Chapter
@{
    ViewBag.Title = "Chapter";
}


<div class="container pb-5">



    <nav aria-label="breadcrumb">
        <div class="row">
            <div class="col-md-9">

                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Library</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a href="#">Chapter 212</a></li>
                </ol>

            </div>
            <div class="col-md-2">

                <div class=" breadcrumb text-center mb-0">

                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item ml-4"> <a href=""><i class="fas fa-bookmark float-md-rigt"></i> </a> </li>
                        <li class="ml-5"> <a href=""><i class="fas fa-adjust float-md-rigt"></i> </a>  </li>
                    </ol>

                </div>

            </div>
        </div>
    </nav>




    <div class="select-picker-pagination">

        <div class="input-group mb-3 w-50 float-left">

            <select class="custom-select" id="inputGroupSelect03">
                <option selected="">Choose...</option>
                <option value="1">Chapter-1  -  A Boy Under The Starry Night</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>



        <div class="select-pagination">
            <div class="row">
                <div class="col-md-6">
                    <div class="nav-links ">
                        <div class="nav-previous float-left">
                            <a href="bestnovel.com/novel/legendary-mechanic/chapter-2" class="btn prev_page">Prev</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="nav-next ">
                        <a href="bestnovel.com/novel/legendary-mechanic/chapter-4" class="btn next_page">Next</a>
                    </div>
                </div>
            </div>


        </div>


    </div>





    <div class="chapter-content font">

        <div class="chapter-title-info">

            <div class="chapter-title pt-5">
                <h2 class="pt-5">Chapter-3: Shadow Panther</h2>
            </div>


            <div class="info-editor">
                <span class="mr-4"><b>Translator:</b>  <i>Challin</i> </span>
                <span> <b>Editor: </b><i> Ali Baran</i> </span>
            </div>

        </div>


        <div class="chapter-content-words mt-5">
            <p>Under the bright dawn light that shone across the plain, the Bennet Castle, once again, revealed its grandiosity for the whole world to see.</p>
            <p>Compared to other castles owned by knights of the same rank, the Bennet Castle was actually a much more extravagant piece of architecture. It was, in a way, what you’d call a ‘work of an era’. It took about ten years for the First Bennett Lord to finish constructing it. And if it wasn’t for the diligent maintenance of those who came after him, there wouldn’t be such a magnificent landmark standing here to this day.</p>
            <p>Due to the incompetence of its successors over the last few generations, the Bennett family was demoted from one of the most prestige Lords in the kingdom to just a family of knights. This was why the Bennetts were always so ashamed when they talked about their past.</p>
            <p>“What did you find?” Abel pulled the rein on his pony, then drew his new dagger from his waist pocket.</p>
            <p>Usually, a shadow panther wouldn’t appear during the daytime. It liked being in the dark, and it liked ambushing its prey while hiding at the side of the road. An encounter like this was rather unusual, in a way. This panther must’ve been starving to go so far away out of the forest.</p>
            <p>Having dug his dagger inside the shadow panther, Abel quickly let go of his grip and took a few steps back. The panther, on the other hand, started violently jerking its body as it laid on the ground.&nbsp;It didn’t have the energy to keep up the fight, but the bloodlust would just never leave its conscience.</p>
            <p>Abel wanted to make sure that the panther was dead, but Norman pulled him back when he took a step forward. “Be careful,” he said, as he threw the sheath of his sword towards the shadow panther.</p>
            <p>Now that the shadow panther was certainly dead, Norman still wouldn’t let Abel go check on it. Instead, he went ahead to pick up the sheath that he threw.</p>
            <p>“Young Master,” he pointed towards the claw marking on his sheath as he picked it up,&nbsp;“As you can see, most beasts prefer killing their prey instantly.”</p>
            <p>Norman picked up the shadow panther’s corpse on the ground. Then, with a smile on his face, he removed the dagger from its backside and returned it back to Abel.</p>
            <p>Under the bright dawn light that shone across the plain, the Bennet Castle, once again, revealed its grandiosity for the whole world to see.</p>
            <p>Compared to other castles owned by knights of the same rank, the Bennet Castle was actually a much more extravagant piece of architecture. It was, in a way, what you’d call a ‘work of an era’. It took about ten years for the First Bennett Lord to finish constructing it. And if it wasn’t for the diligent maintenance of those who came after him, there wouldn’t be such a magnificent landmark standing here to this day.</p>
            <p>Due to the incompetence of its successors over the last few generations, the Bennett family was demoted from one of the most prestige Lords in the kingdom to just a family of knights. This was why the Bennetts were always so ashamed when they talked about their past.</p>
            <p>“What did you find?” Abel pulled the rein on his pony, then drew his new dagger from his waist pocket.</p>
            <p>Usually, a shadow panther wouldn’t appear during the daytime. It liked being in the dark, and it liked ambushing its prey while hiding at the side of the road. An encounter like this was rather unusual, in a way. This panther must’ve been starving to go so far away out of the forest.</p>
            <p>Having dug his dagger inside the shadow panther, Abel quickly let go of his grip and took a few steps back. The panther, on the other hand, started violently jerking its body as it laid on the ground.&nbsp;It didn’t have the energy to keep up the fight, but the bloodlust would just never leave its conscience.</p>
            <p>Abel wanted to make sure that the panther was dead, but Norman pulled him back when he took a step forward. “Be careful,” he said, as he threw the sheath of his sword towards the shadow panther.</p>
            <p>Now that the shadow panther was certainly dead, Norman still wouldn’t let Abel go check on it. Instead, he went ahead to pick up the sheath that he threw.</p>
            <p>“Young Master,” he pointed towards the claw marking on his sheath as he picked it up,&nbsp;“As you can see, most beasts prefer killing their prey instantly.”</p>
            <p>Norman picked up the shadow panther’s corpse on the ground. Then, with a smile on his face, he removed the dagger from its backside and returned it back to Abel.</p>
            <p>“Young Master,” he pointed towards the claw marking on his sheath as he picked it up,&nbsp;“As you can see, most beasts prefer killing their prey instantly.”</p>
            <p>Norman picked up the shadow panther’s corpse on the ground. Then, with a smile on his face, he removed the dagger from its backside and returned it back to Abel.</p>
            <p>Under the bright dawn light that shone across the plain, the Bennet Castle, once again, revealed its grandiosity for the whole world to see.</p>
            <p>Compared to other castles owned by knights of the same rank, the Bennet Castle was actually a much more extravagant piece of architecture. It was, in a way, what you’d call a ‘work of an era’. It took about ten years for the First Bennett Lord to finish constructing it. And if it wasn’t for the diligent maintenance of those who came after him, there wouldn’t be such a magnificent landmark standing here to this day.</p>
            <p>Due to the incompetence of its successors over the last few generations, the Bennett family was demoted from one of the most prestige Lords in the kingdom to just a family of knights. This was why the Bennetts were always so ashamed when they talked about their past.</p>
            <p>“What did you find?” Abel pulled the rein on his pony, then drew his new dagger from his waist pocket.</p>
            <p>Usually, a shadow panther wouldn’t appear during the daytime. It liked being in the dark, and it liked ambushing its prey while hiding at the side of the road. An encounter like this was rather unusual, in a way. This panther must’ve been starving to go so far away out of the forest.</p>
            <p>Having dug his dagger inside the shadow panther, Abel quickly let go of his grip and took a few steps back. The panther, on the other hand, started violently jerking its body as it laid on the ground.&nbsp;It didn’t have the energy to keep up the fight, but the bloodlust would just never leave its conscience.</p>
            <p>Abel wanted to make sure that the panther was dead, but Norman pulled him back when he took a step forward. “Be careful,” he said, as he threw the sheath of his sword towards the shadow panther.</p>
            <p>Now that the shadow panther was certainly dead, Norman still wouldn’t let Abel go check on it. Instead, he went ahead to pick up the sheath that he threw.</p>
            <p>“Young Master,” he pointed towards the claw marking on his sheath as he picked it up,&nbsp;“As you can see, most beasts prefer killing their prey instantly.”</p>
            <p>Norman picked up the shadow panther’s corpse on the ground. Then, with a smile on his face, he removed the dagger from its backside and returned it back to Abel.</p>



        </div>



    </div>







    <div class="select-picker-pagination pb-5">

        <div class="input-group mb-3 w-50 float-left">

            <select class="custom-select" id="inputGroupSelect03">
                <option selected="">Choose...</option>
                <option value="1">Chapter-1  -  A Boy Under The Starry Night</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>



        <div class="select-pagination">
            <div class="row">
                <div class="col-md-6">
                    <div class="nav-links ">
                        <div class="nav-previous float-left">
                            <a href="bestnovel.com/novel/legendary-mechanic/chapter-2" class="btn prev_page">Prev</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="nav-next ">
                        <a href="bestnovel.com/novel/legendary-mechanic/chapter-4" class="btn next_page">Next</a>
                    </div>
                </div>
            </div>


        </div>


    </div>



</div>

BitirmeFin/Kodlar/eBookSiteWebUI/Views/Novel/Details.cshtml
@using eBookSiteWebUI.Entity;
@model Novel
@{
    ViewBag.Title = "Details";
}
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Library</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="#">@Model.Name</a></li>
        </ol>
    </nav>

    <h1 class="pb-3"> <a href="">@Model.Name</a> </h1>

    <div class="row">

        <div class="col-md-3">
            <img src="/theme/img/lm.jpg" class="img-fluid rounded   " />
        </div>

        <div class="col-md-9">
            <div class="row">

                <div class="col-md-6">

                    <div class="summary_content-wrap">
                        <div class="summary_content">

                            <div class="summary_content_item mb-5">
                                <div class="summary-heading float-sm-left mr-4 ">
                                    <h5>Yazar :</h5>
                                </div>
                                <div class="summary-content">
                                    <a href="">@Model.Name</a>
                                </div>
                            </div>

                            <div class="summary_content_item mb-5">
                                <div class="summary-heading float-sm-left mr-4">
                                    <h5>Türler :</h5>
                                </div>
                                <div class="summary-content">
                                    <div class="genres-content">
                                        <a href="">@Model.GenreId</a>,
                                        <a href="">Adventure</a>,
                                        <a href="">Mecha</a>,
                                        <a href="">Sci-fi</a>,
                                        <a href="">Seinen</a>
                                    </div>

                                </div>
                            </div>

                            <div class="summary_content_item mb-5">
                                <div class="summary-heading float-sm-left mr-4">
                                    <h5>Görüntülenme :</h5>
                                </div>
                                <div class="summary-content">
                                    <span> 12012  izlenme</span>
                                </div>
                            </div>

                            <div class="summary_content_item mb-5">
                                <div class="summary-heading float-sm-left mr-4">
                                    <h5>Puan :</h5>
                                </div>
                                <div class="summary-content">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star-half-alt"></i>
                                    <span class="badge badge-success">53</span>
                                </div>
                            </div>



                        </div>

                    </div>
                </div>



                <div class="col-md-6">

                    <div class="summary_content_item mb-5">
                        <div class="summary-heading float-sm-left mr-4">
                            <h5>Durum :</h5>
                        </div>
                        <div class="summary-content">
                            <span class="badge badge-primary">@Model.Status</span>
                        </div>
                    </div>

                    <div class="summary_content_item mb-5">
                        <div class="summary-heading float-sm-left mr-4">
                            <h5>Bölüm Durumu :</h5>
                        </div>
                        <div class="summary-content">
                            <span class="badge badge-primary">1212</span>

                        </div>
                    </div>

                    <div class="summary_content_item mb-5">
                        <div class="summary-heading float-sm-left mr-4">
                            <i class="fas fa-bookmark fa-2x"></i>
                        </div>
                        <div class="summary-content">
                            <span class="badge badge-primary">12 bookmarked</span>

                        </div>
                    </div>

                    <div class="summary_content_item mb-5">
                        <div class="summary-heading float-sm-left mr-4">
                            <i class="fas fa-comments fa-2x"></i>
                        </div>
                        <div class="summary-content">
                            <span class="badge badge-primary">0 comments</span>

                        </div>
                    </div>





                </div>





            </div>

        </div>

    </div>



    <div class="details_content ">
        <i class="fas fa-star fa-2x float-left mr-4 "></i>
        <p class="ozet">ÖZET</p>

        <p>
            @Model.Summary
        </p>



        <div class="summary-readmore">

            <span class="btn btn-link " style="display:inline-block">
                Show More
            </span>


        </div>


    </div>








    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Bölümler</a>

        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Yorumlar</a>

        </li>

    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="listing-chapters mt-5">
                <div>
                    <i class="fas fa-star fa-2x float-left mr-4 "></i>
                    <h4>Son Eklenen Bölümler</h4>
                </div>


                <ul>
                    <!-- Buraya otomatikman gelecek -->

                    <li>
                        <a href="/Novel/Chapter/@Model.Id">Chapter 1277 - Continuous Benefits, Leek Harvesting Skill</a>
                        <span class="chapter-release-date">
                            <i>March 29,2021</i>
                        </span>
                    </li>

                    
                </ul>


                <div class="chapter-readmore">
                    <span class="btn btn-link  chapter-readmore less-chap">Show More</span>
                </div>

            </div>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="chapter-comments">

                <div class="row border border-dark mt-4">
                    <div class="col-md-4 border-right border-dark">

                        <div class="row mt-4 ">
                            <div class="col-md-3"></div>
                            <div class="col-md-6 text-center">
                                <h5>Ali Baran</h5>

                            </div>
                            <div class="col-md-3"></div>
                        </div>


                    </div>

                    <div class="col-md-8 mt-4">
                        <p>
                            Yorumlar bu kısıma yazılacaktır.Yorumlar bu kısıma yazılacaktır.Yorumlar bu kısıma yazılacaktır.Yorumlar bu kısıma yazılacaktır.Yorumlar bu kısıma yazılacaktır.
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

BitirmeFin/Kodlar/eBookSiteWebUI/Views/Novel/GetGenres.cshtml
@using eBookSiteWebUI.Entity;
@model IEnumerable<Genre>
@{ 
    var selectedGenre = Url.RequestContext.RouteData.Values["id"];
}

<div class="list-group">

    <a class="list-group-item " href="/Novel/Index">Tüm Kitaplar</a>
    @foreach (var genre in Model)
    {

        if (selectedGenre != null)
        {
            if (genre.Id == int.Parse(selectedGenre.ToString()))
            {
                <a href="/Novel/Index/@genre.Id" class="list-group-item list-group-item-action active ">
                    @genre.Name
                </a>
            }
            else
            {
                <a href="/Novel/Index/@genre.Id" class="list-group-item list-group-item-action  ">
                    @genre.Name
                </a>
            }
        }
        else
        {
            <a href="/Novel/Index/@genre.Id" class="list-group-item list-group-item-action  ">
                @genre.Name
            </a>
        }



    }
</div>

BitirmeFin/Kodlar/eBookSiteWebUI/Views/Novel/Index.cshtml
@using eBookSiteWebUI.Models;
@model IEnumerable<NovelsModel>
@{
    ViewBag.Title = "Index";
}
<div class=" container">

    

    <div class="row">
        <div class="col-md-3">
            @Html.Action("GetGenres", "Novel")
        </div>

        <div class="col-md-9">
            @if (Model.Count() == 0)
            {
                <div class="alert alert-danger" role="alert">
                    <i class="fas fa-exclamation-circle"></i>
                    Bu kategoride kitap bulunamadı.
                </div>
            }
            else
            {
                <div class="alert alert-secondary" role="alert">
                    
                    <strong>@Model.Count() adet </strong>  kitap bulundu.
                </div>
            }

            @Html.Partial("_NovelList", Model)
        </div>

    </div>

</div>